{% set name = "DAWG" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30d5da3e48b8cbe5ec94c5a202d2962780d3895ba0883123e6788565f71b2953

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dawg

about:
  home: https://github.com/pytries/DAWG
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'DAFSA-based dictionary-like read-only objects for Python'
  doc_url: http://dawg.readthedocs.io

extra:
  recipe-maintainers:
    - mcs07
