travis:
  secure:
    BINSTAR_TOKEN: uN2pp8NgIJNYQUUV5SfrF8iAzJzCBfZRAyLnKQpMgiaUeJ3iLX6HyCtFUOnrkJBmQMpN+vYVGu1/8QMGtk6A7OIw6ingnxZlp5UXZZjc6grmf35tERAGrssqPagLtTuDLV0kcDBY8HMh71g6WksZKBSmuV08/v4njVLN9p5hCzY2t82IyQ2BFOO6+msa0qiVSoKanb6FuFSJUw9kbXTvqdGpK4zgP+QdKjA4lG40ED+pw8C1it/8/Gx+H83Y/3UHdSlr42aORlMo4YaObZFUPxqIGYZCginZ4VW0MB5fSHjo1Ewoure9wSODMi9A/Pq8PyRqnRcydZEsajBU2kAE2ZU7cWFqmPbz+Yc9tRQxVnqQ9SmdmvOojFoIx3YTSdQqPkedx969KCyr1psU0Hw4dpPfz2/agYmu4awLgD0OUAmu6y4gHjE31B0N+djV5JjdaZ41I3z0wPg0vHaJEsvbwizldJksW7gYff30JXim4dIf5h2mFJaLATtWkf8F4vOGUiDt3ib6tdbVhT7LEH11fwid/4cgaNszpOTqMIDWKQRJDUGlLFsLpLn4cq/XmGHJK8hBMdN69BF8xpuWE7nfQXKnd2aNmd6pOvJDBH/uGGH/N0ET6RQincHynbtneyIGXrMnYE/SGllPlut9Bv3WjkPEqSJPCLNK5D5LTx11+tM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
